### ISSUE TITLE
Additional Contributions 

### ISSUE THREAD

**Issue by madtank** [davidshtian/Bedrock-ChatBot-with-LangChain-and-Streamlit#4]
Let me know if there's a way I can get in touch, I'd be interested in contributing more.

**Comment by madtank** [comment]
I've made some updates on my fork with some minor improvements, I think best part of the changes is I get the key values for the prompt automatically. I'd like to do RAG local using cohere for embedding, and knowledge bases. And of course I want to add llama 3 if it works ok for dialog, it doesn't look fine tuned for chat. Let me know if these are things you'd like for me to contribute. https://github.com/madtank/Bedrock-ChatBot-with-LangChain-and-Streamlit/pull/1

**Comment by davidshtian** [comment]
> I've made some updates on my fork with some minor improvements, I think best part of the changes is I get the key values for the prompt automatically. I'd like to do RAG local using cohere for embedding, and knowledge bases. And of course I want to add llama 3 if it works ok for dialog, it doesn't look fine tuned for chat. Let me know if these are things you'd like for me to contribute. [madtank#1](https://github.com/madtank/Bedrock-ChatBot-with-LangChain-and-Streamlit/pull/1)

Great idea~ 🚀 I was thinking about adding RAG part to this repo, while later I thought to keep it simple and clear for using the tools, and I'd be really glad to discuss with you more about them, do you have any personal IM account like Slack? Thanks~

**Comment by madtank** [comment]
> > I've made some updates on my fork with some minor improvements, I think best part of the changes is I get the key values for the prompt automatically. I'd like to do RAG local using cohere for embedding, and knowledge bases. And of course I want to add llama 3 if it works ok for dialog, it doesn't look fine tuned for chat. Let me know if these are things you'd like for me to contribute. [madtank#1](https://github.com/madtank/Bedrock-ChatBot-with-LangChain-and-Streamlit/pull/1)
> 
> Great idea~ 🚀 I was thinking about adding RAG part to this repo, while later I thought to keep it simple and clear for using the tools, and I'd be really glad to discuss with you more about them, do you have any personal IM account like Slack? Thanks~

Maybe discord server?

**Comment by madtank** [comment]
Let me know what works best for you. I can do whatever, but I like discord servers. Are you on any discord servers? 
I have RAG with knowledge bases, but I feel it would be better to add something free. Knowledge bases uses opensearch, and it's actually quite expensive. I'm thinking do some local embedding using cohere or titan, we could have some sample data, and people can do their own embeddings, or change file upload to embedding?

**Comment by davidshtian** [comment]
> Let me know what works best for you. I can do whatever, but I like discord servers. Are you on any discord servers? I have RAG with knowledge bases, but I feel it would be better to add something free. Knowledge bases uses opensearch, and it's actually quite expensive. I'm thinking do some local embedding using cohere or titan, we could have some sample data, and people can do their own embeddings, or change file upload to embedding?

👍 https://discord.gg/rDCkxBb6
